[package]
authors = ["Dean Karn <dean.karn@gmail.com>"]
description = "GitHub Alfred Workflow to quickly search and open repositories."
edition = "2018"
license = "MIT"
name = "github-workflow"
repository = "https://github.com/rust-playground/alfred-workflows-rs/tree/master/github-workflow"
version = "1.1.0"

[[bin]]
name = "github-workflow"
path = "src/bin/main.rs"

[dependencies]
alfred = "4.0.1"
clap = "2.33.0"
dirs = "2.0.2"
failure = "0.1.5"
rusqlite = { version = "0.20.0", features = ["chrono"] }
serde_json = "1.0.40"

[dependencies.chrono]
features = ["serde"]
version = "0.4.7"

[dependencies.reqwest]
features = ["rustls-tls"]
version = "0.9.19"

[dependencies.serde]
features = ["derive"]
version = "1.0.98"

[lib]
name = "github_workflow_lib"
path = "src/lib.rs"
