[package]
authors = ["Dean Karn <dean.karn@gmail.com>"]
license = " MIT"
description = "Datadog Alfred Workflow to search dashboards, screenboards and monitors"
repository = "https://github.com/rust-playground/alfred-workflows-rs/tree/master/datadog-workflow"
edition = "2018"
name = "datadog-workflow"
version = "1.1.0"

[[bin]]
name = "datadog-workflow"
path = "src/bin/main.rs"

[lib]
name = "datadog_workflow_lib"
path = "src/lib.rs"

[dependencies]
alfred = "4.0.1"
chrono = { version = "0.4.7", features = ["serde"]}
clap = "2.33.0"
failure = "0.1.5"
reqwest = "0.9.19"

[dependencies.rusqlite]
features = ["chrono", "bundled"]
version = "0.20.0"

[dependencies.serde]
features = ["derive"]
version = "1.0.89"
